---
name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make image
        if: "!startsWith(github.ref, 'refs/tags/')"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_PUSH_USER }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      - name: Push
        run: make push
        if: "!startsWith(github.ref, 'refs/tags/')"
